# Generated by Django 5.2.17 on 2026-10-09 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0121_b1_section_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='B1RunAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('run_id', models.UUIDField()),
                ('variant_id', models.CharField(max_length=32)),
                ('content_version', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('results', models.JSONField()),
            ],
            options={
                'db_table': 'b1_run_attempts',
                'managed': False,
            },
        ),
    ]
