"""Build the browser catalogue from the same compiled gettext messages."""

import gettext
import json
from pathlib import Path
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    help = "Build browser messages; run compilemessages first."

    def add_arguments(self, parser):
        parser.add_argument("--check", action="store_true", help="Fail if the generated browser catalogue is stale.")
        parser.add_argument("--language", choices=("pl", "en"), default="pl")

    def handle(self, *args, **options):
        language = options["language"]
        catalog = Path(settings.BASE_DIR) / f"locale/{language}/LC_MESSAGES/django.mo"
        try:
            with catalog.open("rb") as source:
                messages = gettext.GNUTranslations(source)
        except OSError as error:
            raise CommandError(f"Compile the {language} gettext catalogue first.") from error
        translations = {key: value for key, value in sorted(messages._catalog.items(), key=lambda item: str(item[0]))
                        if isinstance(key, str) and key and isinstance(value, str)}
        translations.update({key[0]: value for key, value in messages._catalog.items()
                             if isinstance(key, tuple) and key[1] == 0})
        translations = dict(sorted(translations.items()))
        name = "Polish" if language == "pl" else "English"
        output = f"// Generated by manage.py build_ui_catalog.\nwindow.PolskiFlow{name}Messages = " + json.dumps(
            translations, ensure_ascii=False, indent=2
        ) + ";\n"
        destination = Path(settings.BASE_DIR) / f"polskiflow/learning/static/polskiflow/i18n-{language}.js"
        if options["check"]:
            if not destination.exists() or destination.read_text() != output:
                raise CommandError("The browser catalogue is stale. Run build_ui_catalog.")
        else:
            destination.write_text(output)
        self.stdout.write(f"{name} browser catalogue: {len(translations)} messages.")
