const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, 'learning/static/polskiflow/b1-workspace.js'), 'utf8');
const nodes = Object.fromEntries(['answered','total','missing-count','confirm-description','cancel','accept'].map(name => [name,{textContent:'',addEventListener(type,fn){this[type]=fn;}}]));
const inputs = [{type:'radio', checked:false}, {type:'text', value:'  '}];
const questions = inputs.map((input,index)=>({id:'q'+index,querySelectorAll:()=>[input],focus(){this.focused=true;}}));
const missing = {children:[],replaceChildren(){this.children=[];},appendChild(node){this.children.push(node);}};
const dialog = {open:false, showModal(){this.open=true;},close(){this.open=false;},querySelector:s=>nodes[s.match(/data-exam-(.*)\]/)[1]]};
const listeners = {};
const root = {dataset:{phase:'part'},addEventListener(type,fn){this[type]=fn;}};
const form = {querySelectorAll:()=>questions,querySelector:s=>s==='[data-exam-missing]'?missing:s==='[data-exam-confirm]'?dialog:nodes[s.match(/data-exam-(.*)\]/)[1]],addEventListener(type,fn){listeners[type]=fn;},requestSubmit(button){this.submitted=button;listeners.submit({submitter:button});}};
const bar = {closest:()=>form,querySelector:s=>nodes[s.match(/data-exam-(.*)\]/)[1]]};
vm.runInNewContext(source,{document:{querySelector:s=>s==='[data-exam-workspace]'?bar:root,createElement:()=>({addEventListener(type,fn){this[type]=fn;}})},window:{addEventListener(){},setTimeout:fn=>fn()}});
assert.equal(nodes.total.textContent,'2');assert.equal(nodes['missing-count'].textContent,'2');
inputs[0].checked=true;listeners.change();assert.equal(nodes.answered.textContent,'1');assert.equal(missing.children[0].href,'#q1');missing.children[0].click();assert(questions[1].focused);
inputs[1].value='czas';listeners.input();assert.equal(nodes.answered.textContent,'2');
const finish={value:'finish'};let prevented=false,stopped=false;
listeners.submit({submitter:finish,preventDefault(){prevented=true;},stopImmediatePropagation(){stopped=true;}});assert(prevented&&stopped);assert(dialog.open);
nodes.cancel.click();assert(!dialog.open);assert.equal(form.submitted,undefined);
listeners.submit({submitter:finish,preventDefault(){},stopImmediatePropagation(){}});nodes.accept.click();assert.equal(form.submitted,finish);assert(!dialog.open);
listeners.submit({submitter:{value:'skip'},preventDefault(){},stopImmediatePropagation(){}});assert.match(nodes['confirm-description'].textContent,/без балла/);
root.dataset.expired='1';root['b1-run-expired']();assert(!dialog.open);
listeners.submit({submitter:finish,preventDefault(){throw Error('timeout must not be intercepted');}});
console.log('PASS: radio/written answer counts, missing focus, cancelled/confirmed submission, timeout bypass');
